namespace NCDC.Protocol.MySql.Constant;

[Flags]
public enum MySqlCapabilityFlagEnum
{
    CLIENT_LONG_PASSWORD=1,
    
    CLIENT_FOUND_ROWS=1<<1,
    
    CLIENT_LONG_FLAG=1<<2,
    
    CLIENT_CONNECT_WITH_DB=1<<3,
    
    CLIENT_NO_SCHEMA=1<<4,
    
    CLIENT_COMPRESS=1<<5,
    
    CLIENT_ODBC=1<<6,
    
    CLIENT_LOCAL_FILES=1<<7,
    
    CLIENT_IGNORE_SPACE=1<<8,
    
    CLIENT_PROTOCOL_41=1<<9,
    
    CLIENT_INTERACTIVE=1<<10,
    
    CLIENT_SSL=1<<11,
    
    CLIENT_IGNORE_SIGPIPE=1<<12,
    
    CLIENT_TRANSACTIONS=1<<13,
    
    CLIENT_RESERVED=1<<14,
    
    CLIENT_SECURE_CONNECTION=1<<15,
    
    CLIENT_MULTI_STATEMENTS=1<<16,
    
    CLIENT_MULTI_RESULTS=1<<17,
    
    CLIENT_PS_MULTI_RESULTS=1<<18,
    
    CLIENT_PLUGIN_AUTH=1<<19,
    
    CLIENT_CONNECT_ATTRS=1<<20,
    
    CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA=1<<21,
    
    CLIENT_CAN_HANDLE_EXPIRED_PASSWORDS=1<<22,
    
    CLIENT_SESSION_TRACK=1<<23,
    
    CLIENT_DEPRECATE_EOF=1<<24
}